modLoader = "hollowforge"
loaderVersion = "[36,)"
license = "All rights reserved"
[[mods]]
modId = "hc"
version = "${file.jarVersion}"
displayName = "HollowCore"
description = '''
'''
[[dependencies.hc]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.hc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"